# Generated by Django 2.1.2 on 2019-08-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_userregistration_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='CreatedBy',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='CreatedDate',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='EmailService',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='ExpiredDate',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='MobileNo',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='ModifiedBy',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='ModifiedDate',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='Salt',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='StartDate',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='isDeleted',
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='Password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='UserName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='confirm_password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
