# Generated by Django 2.1.5 on 2019-09-09 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_auto_20190905_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='CreatedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='ExpiredDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='ModifiedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='StartDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
