# Generated by Django 2.1.2 on 2019-08-16 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_auto_20190817_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='CreatedBy',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='ExpiredDate',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='ModifiedBy',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='ModifiedDate',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='StartDate',
            field=models.DateTimeField(default=0),
        ),
    ]
