# Generated by Django 2.2.4 on 2019-08-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0006_auto_20190817_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='confirm_password',
            new_name='ConfirmPassword',
        ),
    ]
